### ISSUE TITLE
增加友链页面

### ISSUE THREAD

**Issue by shenghuo2** [QLNU-Sec-Team/QLNU-Sec-Team.github.io#22]
用于跳转其他战队的网站
不过有个问题就是移动端宽度，对于navibar再增加一个元素，可能会不好看
或者弄个burgerMenu？

**Comment by Yalois** [comment]
> 用于跳转其他战队的网站 不过有个问题就是移动端宽度，对于navibar再增加一个元素，可能会不好看 或者弄个burgerMenu？

我觉得可以把navbar调小一点
